name : Novanet-
brand : My Site
description : This is my site
keyword : 
url : https://novanet-.github.io/
email : 
twitter :
github :
author : 
year : 2016
markdown : kramdown
exclude :
  - node_modules
